#!/usr/bin/env python3
"""Generate .htaccess with 301 redirects from legacy_redirects.collect_redirects()."""
from __future__ import annotations

import sys
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SITE))

from legacy_redirects import collect_redirects  # noqa: E402

HTACCESS = SITE / ".htaccess"
HEADER = """# Auto-generated by scripts/gen_legacy_redirects.py — do not edit by hand.
# Rebuild: cd Webseite/site && python3 scripts/gen_legacy_redirects.py

RewriteEngine On
"""


def re_escape_path(path: str) -> str:
    """Regex-safe path segment for RewriteRule (Apache mod_rewrite)."""
    out = path.lstrip("/")
    for ch in ".+*?^${}[]|()\\":
        out = out.replace(ch, f"\\{ch}")
    return "/" + out if path.startswith("/") else out


def render_htaccess(redirects: dict[str, str]) -> str:
    lines = [HEADER.rstrip(), ""]
    for src in sorted(redirects, key=len, reverse=True):
        dst = redirects[src]
        src_no_slash = src.rstrip("/")
        pattern = f"^{re_escape_path(src_no_slash)}/?$"
        target = dst.rstrip("/") + "/" if dst.startswith("http") else dst
        lines.append(f"RewriteRule {pattern} {target} [R=301,L,NC]")

    lines.extend(
        [
            "",
            "# Fallback: strip /de/ prefix for unmapped legacy paths",
            "RewriteRule ^de/(.*)$ /$1/ [R=301,L]",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    redirects = collect_redirects()
    HTACCESS.write_text(render_htaccess(redirects), encoding="utf-8")
    print(f"Wrote {len(redirects)} redirects → {HTACCESS}")


if __name__ == "__main__":
    main()
